ENT.Type = "anim"
ENT.Base = "base_anim"
ENT.PrintName = "MintyRP Bank Teller"
ENT.Author = "MintyRP"
ENT.Category = "MintyRP"
ENT.Spawnable = true
ENT.AdminOnly = true
ENT.Model = "models/player/Group01/male_07.mdl"
ENT.AutomaticFrameAdvance = true
